### ISSUE TITLE
Input control values not being applied

### ISSUE THREAD

**Issue by gpdawson** [DavidWingate/CIFilterBox#2]
I am finding that when trying to edit various input/output values (e.g. CIColorClamp), the app either does not respond to newly entered values, or perhaps is using some historical setting of values. Hence I am seeing very inconsistent output image despite changes I made to the values.

I also notice that values with steppers do seem to respond to changes made with the stepper, but apparently ignores changes that I make to the same values directly by typing in a new value.

Generally, what seems to be needed in general is some change to guarantee that all user changes to values are recognised no matter how entered.

**Comment by DavidWingate** [comment]
I'm having trouble reproducing this issue, would you mind giving me the values typed into the CIColorClamp boxes so that I can test? Thanks.

The difference between values with steppers and values without is that some filters provide a min-max range, so the stepper can know how much to step by. Without the range, the stepper doesn't make a lot of sense!

CIColorClamp only asks for CIVectors, so you have to work out what the min-max values are. In this case it should be from 0.0 to 1.0. Numbers outside of that range would have no additional effects.

I am also having trouble reproducing the stepper box issue. Typing numbers into the box seems to work on my machine. Could you let me know which filter you are using and what numbers you typed into the box? Thanks.

**Comment by gpdawson** [comment]
An example:
1 - I open the app
2 - I click on CIColorClamp (initial min values are 0, 0, 0, 0, max values are 1, 1, 1, 1)
3 - I click focus into the first inputMin value boxes and change min values to 1, 1, 0, 1 using tab to move to next field
There is no change to the displayed output image
4 - I click focus into 3rd min value and change it back from 0 to 1
The displayed output image changes to have only blue pixels (as expected from the first set of values I entered, but I was expecting an all black image now)
5 - I click focus into 3rd min value and change it from 1 to 0, then back to 1 etc but the output image is now back to being identical to the input image and does not change any more no matter how many times I do this

**Comment by DavidWingate** [comment]
I can now reproduce this and I'll work on a fix. Thanks again for the report!

**Comment by DavidWingate** [comment]
The new update (1.0.1) should resolve this issue. Tested the CIColorClamp filter with the above values and it now works as expected on MacOS 12.3.1. Stepper input fields are now working with both the typed value and the stepper. Thanks for the report, and do let me know if you catch any more!

**Comment by gpdawson** [comment]
Yes - the CIColorLamp now responds to my entered values. However, what I'm now finding is that when I later select another filter (e.g. CIColorControls) the right hand side of the split view is then frozen showing the previous filter's image and settings, and clicking on any further filter types in left hand side of split view does nothing. Closing the app and restarting seems to clear this though.

After some further testing I think this might be happening if you move to the next filter before the one you previously selected has had time to render its output image - after that everything is frozen.

**Comment by DavidWingate** [comment]
I'm opening the freezing interface problem as a new issue and working on a fix.
