### ISSUE TITLE
Please make this app available to all global regions

### ISSUE THREAD

**Issue by rehatkathuria** [DavidWingate/CIFilterBox#5]
I'm based in the UK and unable to access the app in my region.

**Comment by DavidWingate** [comment]
Hello, I'm afraid it's not currently available in any region! (I am also based in the UK). I had to pull it from the App Store because it crashes on MacOS Ventura. I am currently working on a complete rewrite, so it will be back but it will probably take a couple of months or so. Sorry for the delay, but the SwiftUI version is just too unstable; the new one will be made with AppKit.

**Comment by rehatkathuria** [comment]
Ah, that's fair! Is the work itself open-sourced anywhere or is it closed?

**Comment by DavidWingate** [comment]
Closed I'm afraid! There is an open source project doing something similar, but it's an iOS app. I've never actually used it, so I can't comment. You can find it here: https://github.com/noahsark769/cifilter.io/tree/master/iOS

**Comment by DavidWingate** [comment]
Version 2.0 is now in the AppStore and is definitely available in your (our) region! Sorry for the wait.

**Comment by rehatkathuria** [comment]
No, please don't apologise –– Thank you for your efforts in making it available in our region!
